### ISSUE TITLE
Guid persistence as Id

### ISSUE THREAD

**Issue by tgiachi** [ttu/json-flatfile-datastore#41] opened 2019-09-17 18:55 UTC
Hi!
I have entity with Id (`keyProperty: nameof(Entity.Id));` as Guid but i receive this error

![image](https://user-images.githubusercontent.com/942730/65070695-66cf7980-d98d-11e9-97f9-3fd571584512.png)
 Can you help me?
Thanks!

**Comment by tlejmi** [comment] 2019-09-17 21:17
assign value to id property using idValue.toSting()  and if you are using EntityFramework Identity customize identity to use int instead of guid.

**Comment by tgiachi** [comment] 2019-09-20 17:31
ok thanks!

**Comment by ttu** [comment] 2019-09-26 19:36
Apparently this was not a bug in JsonFlatFileDataStore? Will close this issue.

If there is something to be fixed please reopen this.

**Closed by ttu** 2019-09-26 19:36 UTC
